format_version: 10
pipelines:
  Build:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-187ac25:
        git: https://github.com/luolong/Registry.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build-and-Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                command: ./gradlew
                working_directory: registry
                run_if: passed
